### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [piotrm35/road_inspection_viewer#1]
@piotrm35  I have tried the plugin with the sample data and haven't figured how to run the plugin. 
Does it have to use images from one folder

In terms of the scope of the plugin is this not what actions can do in QGIS. You can build paths dynamically using the expressions builder.

**Comment by piotrm35** [comment]
This is my simple plugin i decided share with. Yes, it has to use photos from one folder. This is my way of work. If You have a problem with start the plugin, please send me a short description steps You did and maybe a screenshot.

**Comment by NyakudyaA** [comment]
@piotrm35  Please update your plugin with the following
![homepage](https://user-images.githubusercontent.com/2510900/38355509-6746df4c-38bd-11e8-8523-642af2e94f5c.png)

**Comment by piotrm35** [comment]
Done.
